# Variables
@baseUrl = http://localhost:3333

# Health Check
GET {{baseUrl}}/health

###

# Get Rooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de Teste",
  "description": "Descrição da sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get Room Questions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Question
POST {{baseUrl}}/rooms/66a7f365-128d-4d40-8b53-782f6ac1aef3/questions
Content-Type: application/json

{
  "question": "O que é Vue.js e qual sua diferença em relação ao Angular?"
}

###