import { zodResolver } from "@hookform/resolvers/zod";
import { Loader2 } from "lucide-react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import { Form } from "@/components/ui/form";
import { useCreateQuestion } from "@/http/use-create-question";
import { FormInput } from "./form/form-input";

const createQuestionSchema = z.object({
	question: z
		.string()
		.min(1, "Question is mandatory")
		.min(10, "Question should have at least 10 characters.")
		.max(500, "Question should have up to 500 characters"),
});

type CreateQuestionFormData = z.infer<typeof createQuestionSchema>;

interface QuestionFormProps {
	roomId: string;
}

export function QuestionForm({ roomId }: QuestionFormProps) {
	const { mutateAsync: createQuestion, isPending: isCreatingQuestion } =
		useCreateQuestion(roomId);

	const form = useForm<CreateQuestionFormData>({
		resolver: zodResolver(createQuestionSchema),
		defaultValues: {
			question: "",
		},
	});

	function handleCreateQuestion(data: CreateQuestionFormData) {
		createQuestion(data);

		form.reset();
	}

	return (
		<Card>
			<CardHeader>
				<CardTitle>Make a question</CardTitle>
				<CardDescription>
					Type your question below to receive a reply generated by AI.
				</CardDescription>
			</CardHeader>
			<CardContent>
				<Form {...form}>
					<form
						className="flex flex-col gap-4"
						onSubmit={form.handleSubmit(handleCreateQuestion)}
					>
						<FormInput<CreateQuestionFormData>
							label="Your question"
							name="question"
							formControl={form.control}
							placeholder="What would you like to know?"
							type="textarea"
							fieldClassName="min-h-[100px]"
						/>

						<Button type="submit" disabled={isCreatingQuestion}>
							{isCreatingQuestion ? (
								<p className="flex items-center p-2">
									<Loader2 className="animate-spin" /> Submiting your question
								</p>
							) : (
								"Submit your question"
							)}
						</Button>
					</form>
				</Form>
			</CardContent>
		</Card>
	);
}
